// Autogenerated from Pigeon (v25.5.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, unnecessary_import, no_leading_underscores_for_local_identifiers
// ignore_for_file: avoid_relative_lib_imports
import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;
import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';

import 'package:quick_blue/src/messages.g.dart';


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is PlatformBleInputProperty) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is PlatformBleOutputProperty) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is PlatformConnectionState) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is PlatformGattStatus) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is PlatformCompanionDevice) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformScanResult) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformConnectionStateChange) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformServiceDiscovered) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformMtuChange) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformCharacteristicValueChanged) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is PlatformL2CapSocketEvent) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PlatformBleInputProperty.values[value];
      case 130: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PlatformBleOutputProperty.values[value];
      case 131: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PlatformConnectionState.values[value];
      case 132: 
        final int? value = readValue(buffer) as int?;
        return value == null ? null : PlatformGattStatus.values[value];
      case 133: 
        return PlatformCompanionDevice.decode(readValue(buffer)!);
      case 134: 
        return PlatformScanResult.decode(readValue(buffer)!);
      case 135: 
        return PlatformConnectionStateChange.decode(readValue(buffer)!);
      case 136: 
        return PlatformServiceDiscovered.decode(readValue(buffer)!);
      case 137: 
        return PlatformMtuChange.decode(readValue(buffer)!);
      case 138: 
        return PlatformCharacteristicValueChanged.decode(readValue(buffer)!);
      case 139: 
        return PlatformL2CapSocketEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

const StandardMethodCodec pigeonMethodCodec = StandardMethodCodec(_PigeonCodec());
