name: quick_blue_darwin
description: darwin implementation of the quick_blue plugin.
version: 0.4.0-dev.0

environment:
  sdk: ^3.7.0
  flutter: 3.29.0

dependencies:
  quick_blue_platform_interface: ^0.4.0-dev.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  pigeon: ^25.5.0

dependency_overrides:
  quick_blue_platform_interface:
    path: ../quick_blue_platform_interface

flutter:
  plugin:
    implements: quick_blue
    platforms:
      macos:
        pluginClass: QuickBlueDarwinPlugin
        dartPluginClass: QuickBlueDarwin
        sharedDarwinSource: true
      ios:
        pluginClass: QuickBlueDarwinPlugin
        dartPluginClass: QuickBlueDarwin
        sharedDarwinSource: true
